# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Andrej Guran Blog
  avatar: "https://avatars3.githubusercontent.com/u/1847466?v=3&s=460"
  gravatar: # Email MD5 hash
  description: "Andrej Guran personal website with blog posts about programing living in berlin and everything" # used by search engines

  # Header and footer text
  header_text: >
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

     <p>Remove all header text in <code>_config.yml</code> to disable this feature.</p>
  header_text_feature_image:
  footer_text: >
   © 2015 Andrej Guran, <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: "andrej.guran@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "andrejguran"
  flickr:
  github: "andrejguran"
  google_plus:
  instagram:
  linkedin:  "http://linked.in/andrejguran"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "andrejguran"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-64288033-1"
  disqus_shortname: "andrejgurangithubpages"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
